name: Build iOS Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "NAME=my-gdps-name" >> $GITHUB_ENV
          echo "BUNDLE_ID=my.bundle.id" >> $GITHUB_ENV
          echo "URL=https://example.com/myurl" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: node index.js
